// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://parsingexcel/");
    driver.manage().window().setSize(new Dimension(1345, 792));
    driver.findElement(By.cssSelector(".navbar-nav > .nav-link:nth-child(1)")).click();
    driver.findElement(By.name("login")).click();
    driver.findElement(By.name("login")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("admin");
    driver.findElement(By.cssSelector(".form")).click();
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    driver.findElement(By.id("navbarSupportedContent")).click();
    driver.findElement(By.linkText("Успеваемость")).click();
    driver.findElement(By.id("r0c0")).click();
    driver.findElement(By.id("r0c0")).sendKeys("4");
    driver.findElement(By.id("r1c1")).click();
    driver.findElement(By.id("r1c1")).sendKeys("4");
    driver.findElement(By.id("r2c1")).click();
    driver.findElement(By.id("r2c1")).sendKeys("4");
    driver.findElement(By.id("r2c2")).click();
    driver.findElement(By.id("r2c2")).sendKeys("4");
    driver.findElement(By.id("r2c3")).click();
    driver.findElement(By.id("r2c3")).sendKeys("4");
    driver.findElement(By.id("r0c1")).click();
    driver.findElement(By.id("r0c1")).sendKeys("4");
    driver.findElement(By.id("r0c4")).click();
    driver.findElement(By.id("r0c4")).sendKeys("4");
    driver.findElement(By.id("r1c4")).click();
    driver.findElement(By.id("r1c4")).sendKeys("4");
    driver.findElement(By.id("r1c5")).click();
    driver.findElement(By.id("r1c5")).sendKeys("4");
    driver.findElement(By.id("r1c6")).click();
    driver.findElement(By.id("r1c6")).sendKeys("4");
    driver.findElement(By.id("r0c6")).click();
    driver.findElement(By.id("r0c6")).sendKeys("4");
    driver.findElement(By.id("r0c7")).click();
    driver.findElement(By.id("r0c7")).sendKeys("4");
    driver.findElement(By.id("r0c8")).click();
    driver.findElement(By.id("r0c8")).sendKeys("4");
    driver.findElement(By.id("r0c9")).click();
    driver.findElement(By.id("r0c9")).sendKeys("4");
    driver.findElement(By.id("r0c5")).click();
    driver.findElement(By.id("r0c5")).sendKeys("4");
    driver.findElement(By.id("r0c3")).click();
    driver.findElement(By.id("r0c3")).sendKeys("4");
    driver.findElement(By.id("r0c2")).click();
    driver.findElement(By.id("r0c2")).sendKeys("4");
    driver.findElement(By.name("submit_excel")).click();
    driver.findElement(By.cssSelector(".nav-link:nth-child(2) > img")).click();
    driver.close();
  }
}
